// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/management/device.proto

package management

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _device_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on EnrollDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *EnrollDeviceRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 127 {
		return EnrollDeviceRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 127 runes, inclusive",
		}
	}

	if l := utf8.RuneCountInString(m.GetDeviceId()); l < 1 || l > 127 {
		return EnrollDeviceRequestValidationError{
			field:  "DeviceId",
			reason: "value length must be between 1 and 127 runes, inclusive",
		}
	}

	if err := m._validateUuid(m.GetTenantId()); err != nil {
		return EnrollDeviceRequestValidationError{
			field:  "TenantId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	if m.GetClient() == nil {
		return EnrollDeviceRequestValidationError{
			field:  "Client",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetClient()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EnrollDeviceRequestValidationError{
				field:  "Client",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Credential

	return nil
}

func (m *EnrollDeviceRequest) _validateUuid(uuid string) error {
	if matched := _device_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// EnrollDeviceRequestValidationError is the validation error returned by
// EnrollDeviceRequest.Validate if the designated constraints aren't met.
type EnrollDeviceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnrollDeviceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnrollDeviceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnrollDeviceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnrollDeviceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnrollDeviceRequestValidationError) ErrorName() string {
	return "EnrollDeviceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e EnrollDeviceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnrollDeviceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnrollDeviceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnrollDeviceRequestValidationError{}

// Validate checks the field values on DeviceResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *DeviceResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for DeviceId

	return nil
}

// DeviceResponseValidationError is the validation error returned by
// DeviceResponse.Validate if the designated constraints aren't met.
type DeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceResponseValidationError) ErrorName() string { return "DeviceResponseValidationError" }

// Error satisfies the builtin error interface
func (e DeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceResponseValidationError{}

// Validate checks the field values on DeviceGetWhoAmIRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DeviceGetWhoAmIRequest) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// DeviceGetWhoAmIRequestValidationError is the validation error returned by
// DeviceGetWhoAmIRequest.Validate if the designated constraints aren't met.
type DeviceGetWhoAmIRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceGetWhoAmIRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceGetWhoAmIRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceGetWhoAmIRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceGetWhoAmIRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceGetWhoAmIRequestValidationError) ErrorName() string {
	return "DeviceGetWhoAmIRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeviceGetWhoAmIRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceGetWhoAmIRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceGetWhoAmIRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceGetWhoAmIRequestValidationError{}
